# Generated by Django 3.2.16 on 2023-02-12 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.UUIDField(db_index=True, default=uuid.UUID('b7682add-cf46-41b6-b0e2-990e828c61a2'), editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=16, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('visibility', models.CharField(blank=True, default='Unlisted', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teams',
                'managed': True,
            },
        ),
    ]
