# Generated by Django 3.2.16 on 2023-02-12 21:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hcunits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
        migrations.AddField(
            model_name='team',
            name='point_limit',
            field=models.IntegerField(blank=True, default=300, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='age',
            field=models.CharField(choices=[('modern', 'Modern'), ('golden', 'Golden')], default='modern', max_length=6),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('2615c42f-c416-4676-a28d-cedc415de6b4'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='visibility',
            field=models.CharField(choices=[('unlisted', 'Unlisted'), ('public', 'Public')], default='unlisted', max_length=16),
        ),
    ]
