# Generated by Django 3.2.16 on 2023-02-12 23:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hcunits', '0002_auto_20230212_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='starting_force',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('c3fc8473-b843-4f49-b98c-996f2de74f6a'), editable=False, unique=True),
        ),
    ]
