# Generated by Django 3.2.16 on 2023-02-14 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hcunits', '0003_auto_20230212_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='maps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='team',
            name='object_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='team',
            name='sideline',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='team',
            name='tarot_cards',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='team',
            name='starting_force',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('3f67bef8-4d97-409d-8d60-6d45eab45394'), editable=False, unique=True),
        ),
    ]
