# Generated by Django 3.2.16 on 2023-02-15 01:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hcunits', '0004_auto_20230214_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='starting_force',
            new_name='main_force',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('615551d9-fce4-467c-b5a0-74a51bdfe236'), editable=False, unique=True),
        ),
    ]
