# Generated by Django 3.2.16 on 2023-02-15 02:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hcunits', '0005_auto_20230215_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='main_force',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('16c72254-93b2-47d8-babf-a0ce6d2470b1'), editable=False, unique=True),
        ),
    ]
