# Generated by Django 3.2.16 on 2023-02-16 04:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hcunits', '0008_auto_20230216_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('87b0f898-e7ff-439e-aba4-2b7187c32bff'), editable=False, unique=True),
        ),
    ]
