# Generated by Django 3.2.16 on 2023-02-16 17:39

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hcunits', '0009_alter_team_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('be472bb4-b6a6-495a-bc57-655aac267fa6'), editable=False, unique=True),
        ),
    ]
