# Generated by Django 3.2.16 on 2023-02-22 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hcunits', '0012_alter_team_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('11d7c9af-d5cf-4f76-8043-6c7365a4d937'), editable=False, unique=True),
        ),
    ]
